ALTER TABLE users
    ADD COLUMN IF NOT EXISTS warrior_affinity NUMERIC(12,2) NOT NULL DEFAULT 0;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS mage_affinity NUMERIC(12,2) NOT NULL DEFAULT 0;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS templar_affinity NUMERIC(12,2) NOT NULL DEFAULT 0; 

