/**
 * Instagram Analyzer Stub
 * Local analysis without external data access
 * 
 * ⚠️ STUB IMPLEMENTATION - NO EXTERNAL CALLS
 * This service provides placeholder analysis using only the handle as input.
 * No Instagram data is fetched, scraped, or accessed externally.
 */

const { createLogger } = require('../../utils/logger');

const logger = createLogger('InstagramAnalyzerStub');

class InstagramAnalyzerStub {
  constructor() {
    this.analysisCache = new Map();
  }

  /**
   * Generate deterministic analysis based on handle only
   * @param {object} params - Analysis parameters
   * @param {string} params.handle - Instagram handle
   * @param {string} params.url - Instagram URL (optional)
   * @returns {object} Analysis result with summary and openers
   */
  async analyze({ handle, url }) {
    if (!handle) {
      throw new Error('Instagram handle is required for analysis');
    }

    // Use handle as seed for deterministic results
    const seed = this.generateSeed(handle);
    const analysis = this.generateStubAnalysis(handle, seed);

    logger.info('Generated stub analysis', { 
      handle, 
      summaryLength: analysis.summary.length,
      openersCount: analysis.openers.length 
    });

    return analysis;
  }

  /**
   * Generate a numeric seed from handle string
   * @param {string} handle - Instagram handle
   * @returns {number} Numeric seed
   */
  generateSeed(handle) {
    let seed = 0;
    for (let i = 0; i < handle.length; i++) {
      seed = ((seed << 5) - seed + handle.charCodeAt(i)) & 0xffffffff;
    }
    return Math.abs(seed);
  }

  /**
   * Generate stub analysis based on handle and seed
   * @param {string} handle - Instagram handle
   * @param {number} seed - Numeric seed
   * @returns {object} Analysis with summary and openers
   */
  generateStubAnalysis(handle, seed) {
    const templates = {
      summaries: [
        `Stub analysis for @${handle}: Based on handle patterns, this appears to be a creative individual with varied interests. No external data was accessed for this analysis.`,
        `Handle analysis for @${handle}: The username suggests someone who values authenticity and personal branding. This is a placeholder analysis without external data.`,
        `Instagram stub for @${handle}: Username indicates someone who enjoys sharing life moments and connecting with others. Analysis generated locally without data access.`,
        `Profile insight for @${handle}: Handle pattern suggests an active social media user with diverse interests. This is a deterministic stub analysis.`,
        `Creative analysis for @${handle}: Username structure indicates someone who values self-expression and visual storytelling. No external data pulled.`
      ],
      openers: [
        `"Hey! Saw some creative vibes on your profile—what's your go-to weekend adventure?"`,
        `"If you had a day with zero plans, what would you do first?"`,
        `"Your posts always catch my eye—what inspires your creativity?"`,
        `"Random question: what's the most spontaneous thing you've done recently?"`,
        `"I love seeing people's passions come through—what gets you most excited?"`,
        `"Your feed has such good energy—what's your secret to staying positive?"`,
        `"If you could travel anywhere right now, where would you go?"`,
        `"What's something you're really proud of that most people don't know about?"`
      ]
    };

    // Use seed to select deterministic templates
    const summaryIndex = seed % templates.summaries.length;
    const openerIndices = [
      seed % templates.openers.length,
      (seed + 1) % templates.openers.length
    ];

    // Ensure we get 2 different openers
    if (openerIndices[0] === openerIndices[1]) {
      openerIndices[1] = (openerIndices[1] + 1) % templates.openers.length;
    }

    return {
      summary: templates.summaries[summaryIndex],
      openers: [
        templates.openers[openerIndices[0]],
        templates.openers[openerIndices[1]]
      ],
      disclaimer: 'Generated by local stub (no external data accessed)',
      lastAnalyzed: new Date().toISOString()
    };
  }

  /**
   * Get cached analysis if available
   * @param {string} handle - Instagram handle
   * @returns {object|null} Cached analysis or null
   */
  getCachedAnalysis(handle) {
    return this.analysisCache.get(handle) || null;
  }

  /**
   * Cache analysis result
   * @param {string} handle - Instagram handle
   * @param {object} analysis - Analysis result
   */
  cacheAnalysis(handle, analysis) {
    this.analysisCache.set(handle, {
      ...analysis,
      cachedAt: new Date().toISOString()
    });
  }

  /**
   * Clear cache (for testing or memory management)
   */
  clearCache() {
    this.analysisCache.clear();
    logger.info('Analysis cache cleared');
  }

  /**
   * Get cache statistics
   * @returns {object} Cache stats
   */
  getCacheStats() {
    return {
      size: this.analysisCache.size,
      handles: Array.from(this.analysisCache.keys())
    };
  }
}

// Export singleton instance
module.exports = new InstagramAnalyzerStub();
