// ═══════════════════════════════════════════════════════════════════════════════
// TENSEY CHALLENGES - 567 Advanced Embodied Connection Challenges
// Organized by Intensity Level (Low → High Tension)
// ═══════════════════════════════════════════════════════════════════════════════

const CHALLENGES = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // LEVEL 1: BASIC APPROACH & WARM-UP (idx 0-49, 50 challenges)
  // ═══════════════════════════════════════════════════════════════════════════════
  { idx: 0, level: 1, text: 'Say hello to 100 people in a day' },
  { idx: 1, level: 1, text: 'Compliment 5 people on something specific' },
  { idx: 2, level: 1, text: 'Approach someone and find out 3 things about them' },
  { idx: 3, level: 1, text: 'Hold eye contact with 20 strangers for 10 seconds each' },
  { idx: 4, level: 1, text: 'Greet 20 strangers with a genuine smile and "good morning/afternoon"' },
  { idx: 5, level: 1, text: 'Ask 10 people for the time, maintaining eye contact' },
  { idx: 6, level: 1, text: 'Give sincere compliments to 3 people on their style' },
  { idx: 7, level: 1, text: 'Stand in a busy area and practice belly breathing for 5 minutes' },
  { idx: 8, level: 1, text: 'Walk through a crowded space while maintaining grounded presence' },
  { idx: 9, level: 1, text: 'Practice saying "hi" with full body relaxation to 30 people' },
  { idx: 10, level: 1, text: 'Ask 5 strangers about their day and genuinely listen' },
  { idx: 11, level: 1, text: 'Hold a conversation with relaxed jaw for 10 minutes' },
  { idx: 12, level: 1, text: 'Maintain soft eye contact while complimenting someone\'s energy' },
  { idx: 13, level: 1, text: 'Approach 5 people and ask what makes them happy' },
  { idx: 14, level: 1, text: 'Practice mirroring someone\'s energy in conversation' },
  { idx: 15, level: 1, text: 'Sing your favorite song in public with a hat out' },
  { idx: 16, level: 1, text: 'Tell 5 jokes in a day to different people' },
  { idx: 17, level: 1, text: 'Ask someone to teach you a dance in public' },
  { idx: 18, level: 1, text: 'Carry a "Free Hugs" sign and offer hugs to strangers' },
  { idx: 19, level: 1, text: 'Give high-fives to 10 random strangers in a row' },
  { idx: 20, level: 1, text: 'Walk up to a stranger and declare "You\'ve won!" with a high-five' },
  { idx: 21, level: 1, text: 'Ask for directions but keep interrupting with random compliments' },
  { idx: 22, level: 1, text: 'Eavesdrop on a conversation and join in naturally' },
  { idx: 23, level: 1, text: 'Ask a couple for relationship advice' },
  { idx: 24, level: 1, text: 'Share one thing you appreciate about your day with 5 strangers' },
  { idx: 25, level: 1, text: 'Ask for a bite of someone\'s food with playful energy' },
  { idx: 26, level: 1, text: 'Buy a chocolate bar and offer pieces to strangers' },
  { idx: 27, level: 1, text: 'Ask 3 people what their superpower would be' },
  { idx: 28, level: 1, text: 'Start a slow clap in a public place' },
  { idx: 29, level: 1, text: 'Approach someone and ask them to give you a nickname' },
  { idx: 30, level: 1, text: 'Practice walking with "turned on" energy through a mall' },
  { idx: 31, level: 1, text: 'Stand still for 3 minutes in public, feeling into your body' },
  { idx: 32, level: 1, text: 'Ask strangers what they think the best invention is' },
  { idx: 33, level: 1, text: 'Walk around and ask people if they\'ve "found happiness yet"' },
  { idx: 34, level: 1, text: 'Offer someone a "lucky penny" with genuine warmth' },
  { idx: 35, level: 1, text: 'Ask people what their life hacks are' },
  { idx: 36, level: 1, text: 'Start skipping instead of walking and invite others' },
  { idx: 37, level: 1, text: 'Hand out imaginary flyers with full commitment' },
  { idx: 38, level: 1, text: 'Pretend to be a statue for 5 minutes, then suddenly move' },
  { idx: 39, level: 1, text: 'Practice "quinta walk" (heart-led walking) through a busy area' },
  { idx: 40, level: 1, text: 'Ask someone to help you settle a silly debate' },
  { idx: 41, level: 1, text: 'Give someone an on-the-spot compliment that feels vulnerable' },
  { idx: 42, level: 1, text: 'Ask strangers to share their definition of love' },
  { idx: 43, level: 1, text: 'Practice shoulder-down, chest-open posture while talking to 5 people' },
  { idx: 44, level: 1, text: 'Ask someone about their dreams (literal or figurative)' },
  { idx: 45, level: 1, text: 'Approach someone and ask what their superpower is' },
  { idx: 46, level: 1, text: 'Walk around with grounded, magnetic presence for 20 minutes' },
  { idx: 47, level: 1, text: 'Practice speaking from your belly (lower diaphragm) to 10 people' },
  { idx: 48, level: 1, text: 'Ask 3 people what brings them alive' },
  { idx: 49, level: 1, text: 'Maintain open heart posture during 5 full conversations' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEVEL 2: SOCIAL CREATIVITY & PLAYFULNESS (idx 50-119, 70 challenges)
  // ═══════════════════════════════════════════════════════════════════════════════
  { idx: 50, level: 2, text: 'Ask someone to teach you a dance move right now' },
  { idx: 51, level: 2, text: 'Pretend to be a magician and perform a silly trick' },
  { idx: 52, level: 2, text: 'Challenge a stranger to thumb war' },
  { idx: 53, level: 2, text: 'Start freestyle rapping to someone on the street' },
  { idx: 54, level: 2, text: 'Speak to strangers in a made-up language' },
  { idx: 55, level: 2, text: 'Do jumping jacks with a group of girls you approach' },
  { idx: 56, level: 2, text: 'Wear pajamas in a busy area for an hour' },
  { idx: 57, level: 2, text: 'Practice "do I like her/does she like me" awareness with 10 approaches' },
  { idx: 58, level: 2, text: 'Walk backward for an entire block while talking to people' },
  { idx: 59, level: 2, text: 'Balance an object on your head while approaching people' },
  { idx: 60, level: 2, text: 'Pretend to be a celebrity asking for selfies' },
  { idx: 61, level: 2, text: 'Narrate someone\'s actions in sports commentator voice' },
  { idx: 62, level: 2, text: 'Ask someone to help you practice awkward silences' },
  { idx: 63, level: 2, text: 'Give someone a fortune-telling session with playful energy' },
  { idx: 64, level: 2, text: 'Pretend to be a tour guide giving a fake tour' },
  { idx: 65, level: 2, text: 'Ask someone to join imaginary hopscotch' },
  { idx: 66, level: 2, text: 'Interview someone for a fake TV show' },
  { idx: 67, level: 2, text: 'Carry a giant stuffed animal and ask people to hug it' },
  { idx: 68, level: 2, text: 'Start narrating an elevator ride as a rollercoaster' },
  { idx: 69, level: 2, text: 'Pretend to give a dramatic award speech to people around you' },
  { idx: 70, level: 2, text: 'Ask strangers if they\'d like to hear your life story' },
  { idx: 71, level: 2, text: 'Have a conversation using only movie quotes' },
  { idx: 72, level: 2, text: 'Ask for directions to a fictional place (Narnia, Hogwarts)' },
  { idx: 73, level: 2, text: 'Pretend you\'re a mime and copy someone\'s movements' },
  { idx: 74, level: 2, text: 'Offer a "petition to save the dinosaurs"' },
  { idx: 75, level: 2, text: 'Start a silly dance in public and invite others' },
  { idx: 76, level: 2, text: 'Begin doing exaggerated yoga poses on a street corner' },
  { idx: 77, level: 2, text: 'Shout "Plot twist!" and walk away dramatically' },
  { idx: 78, level: 2, text: 'Give a motivational speech to strangers' },
  { idx: 79, level: 2, text: 'Challenge someone to rock-paper-scissors best of 7' },
  { idx: 80, level: 2, text: 'Ask someone to give you a dare on the spot' },
  { idx: 81, level: 2, text: 'Walk in slow motion for 2 minutes in a crowded place' },
  { idx: 82, level: 2, text: 'Play an invisible instrument and start a "band"' },
  { idx: 83, level: 2, text: 'Ask someone to name their favorite song and hum it back' },
  { idx: 84, level: 2, text: 'Ask strangers if they know the secret to happiness' },
  { idx: 85, level: 2, text: 'Create a new secret handshake with someone' },
  { idx: 86, level: 2, text: 'Ask to practice "awkward first date" scenarios' },
  { idx: 87, level: 2, text: 'Walk around with open umbrella indoors' },
  { idx: 88, level: 2, text: 'Pretend to be a detective looking for a missing sock' },
  { idx: 89, level: 2, text: 'Introduce yourself with a made-up accent to 5 people' },
  { idx: 90, level: 2, text: 'Stand on a bench and lecture on tying shoes' },
  { idx: 91, level: 2, text: 'Offer imaginary balloons to people' },
  { idx: 92, level: 2, text: 'Start an impromptu "follow the leader" game' },
  { idx: 93, level: 2, text: 'Walk with a magnifying glass inspecting objects' },
  { idx: 94, level: 2, text: 'Start humming and get people to join' },
  { idx: 95, level: 2, text: 'Pretend to film a cooking show in public' },
  { idx: 96, level: 2, text: 'Host an imaginary game show with trivia' },
  { idx: 97, level: 2, text: 'Walk with an empty picture frame asking for portraits' },
  { idx: 98, level: 2, text: 'Set up imaginary art gallery explaining invisible paintings' },
  { idx: 99, level: 2, text: 'March through public space starting a parade' },
  { idx: 100, level: 2, text: 'Carry around bowl of cereal eating while walking' },
  { idx: 101, level: 2, text: 'Break into spontaneous song and dance (musical audition)' },
  { idx: 102, level: 2, text: 'Lead a conga line and see how many join' },
  { idx: 103, level: 2, text: 'Dress as royalty and ask people to bow' },
  { idx: 104, level: 2, text: 'Walk around with blow-up mattress asking people to test it' },
  { idx: 105, level: 2, text: 'Pretend to conduct an orchestra, inviting others' },
  { idx: 106, level: 2, text: 'Set up "instant karaoke booth" with portable speaker' },
  { idx: 107, level: 2, text: 'Walk with briefcase handcuffed to wrist acting secretive' },
  { idx: 108, level: 2, text: 'Challenge stranger to public roast battle' },
  { idx: 109, level: 2, text: 'Pretend to be famous author signing invisible books' },
  { idx: 110, level: 2, text: 'Carry life-sized celebrity cutout introducing "them"' },
  { idx: 111, level: 2, text: 'Talk into walkie-talkie coordinating "secret operation"' },
  { idx: 112, level: 2, text: 'Wear cape and pretend to read minds' },
  { idx: 113, level: 2, text: 'Dress as butler offering to serve random people' },
  { idx: 114, level: 2, text: 'Bring megaphone selling imaginary products' },
  { idx: 115, level: 2, text: 'Create fake march for absurd cause with chanting' },
  { idx: 116, level: 2, text: 'Walk with bouquet dramatically gifting to strangers' },
  { idx: 117, level: 2, text: 'Carry live fish in bowl asking people to name it' },
  { idx: 118, level: 2, text: 'Pretend invisible friend is with you and introduce them' },
  { idx: 119, level: 2, text: 'Walk around offering "investments" with toy money briefcase' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEVEL 3: VULNERABILITY & AUTHENTIC EXPRESSION (idx 120-199, 80 challenges)
  // ═══════════════════════════════════════════════════════════════════════════════
  { idx: 120, level: 3, text: 'Share an embarrassing fact about yourself with a stranger' },
  { idx: 121, level: 3, text: 'Shout out one of your challenging insecurities in public' },
  { idx: 122, level: 3, text: 'Practice "making jokes about your insecurities" to 3 strangers' },
  { idx: 123, level: 3, text: 'Tell someone a story about a time you felt worthless, then laugh' },
  { idx: 124, level: 3, text: 'Challenge someone to staring contest and lose on purpose' },
  { idx: 125, level: 3, text: 'Start laughing uncontrollably in public' },
  { idx: 126, level: 3, text: 'Walk up to someone you\'re attracted to and admit you\'re nervous' },
  { idx: 127, level: 3, text: 'Share your "worst approach story" with someone you just met' },
  { idx: 128, level: 3, text: 'Ask someone what they\'re afraid of, then share yours' },
  { idx: 129, level: 3, text: 'Admit to 5 people something you\'re insecure about today' },
  { idx: 130, level: 3, text: 'Practice "I don\'t give a fuck what you think" exercise while approaching' },
  { idx: 131, level: 3, text: 'Stand in public and describe out loud what you\'re feeling in your body' },
  { idx: 132, level: 3, text: 'Approach someone and say "I\'m practicing being vulnerable"' },
  { idx: 133, level: 3, text: 'Share with a stranger one thing you don\'t like about yourself' },
  { idx: 134, level: 3, text: 'Ask someone "do you ever feel like you\'re not enough?" and discuss' },
  { idx: 135, level: 3, text: 'Tell 3 people about a recent rejection you experienced' },
  { idx: 136, level: 3, text: 'Practice "welcoming worthlessness feelings" before 5 approaches' },
  { idx: 137, level: 3, text: 'Share your "women resentment" story with a female model/friend' },
  { idx: 138, level: 3, text: 'Admit to someone attractive that you find them intimidating' },
  { idx: 139, level: 3, text: 'Practice saying "I want to fuck" out loud in private, then speak to someone' },
  { idx: 140, level: 3, text: 'Tell someone about your relationship with your mother' },
  { idx: 141, level: 3, text: 'Share one thing you\'re ashamed of with a trusted person' },
  { idx: 142, level: 3, text: 'Practice "are you?" exercise - ask someone then sit in silence' },
  { idx: 143, level: 3, text: 'Describe your sexual fantasy to someone you trust (or in writing publicly)' },
  { idx: 144, level: 3, text: 'Stand in public and practice "existential kink" - moan about something hard' },
  { idx: 145, level: 3, text: 'Share your "harms list" insights with someone' },
  { idx: 146, level: 3, text: 'Practice "I\'m a sexual being" affirmation before approaching someone' },
  { idx: 147, level: 3, text: 'Tell someone about a time you felt rejected by a woman' },
  { idx: 148, level: 3, text: 'Share what you\'re "walling off" emotionally with someone' },
  { idx: 149, level: 3, text: 'Practice "only saying statements, no questions" for 10 minutes' },
  { idx: 150, level: 3, text: 'Tell someone the story of your "worst heartbreak"' },
  { idx: 151, level: 3, text: 'Ask someone "what would you do to me if I was yours?" (playful context)' },
  { idx: 152, level: 3, text: 'Share one limiting belief about yourself with a stranger' },
  { idx: 153, level: 3, text: 'Practice "feeling tension without fixing it" in conversation' },
  { idx: 154, level: 3, text: 'Tell a woman something you appreciate about feminine energy' },
  { idx: 155, level: 3, text: 'Share your biggest fear about relationships' },
  { idx: 156, level: 3, text: 'Practice "sitting in discomfort" for 3 minutes during a conversation' },
  { idx: 157, level: 3, text: 'Ask someone to tell you something hard to hear about yourself' },
  { idx: 158, level: 3, text: 'Share one way your parents\' relationship affected you' },
  { idx: 159, level: 3, text: 'Practice "no words - just eye contact and breath" with someone for 2 min' },
  { idx: 160, level: 3, text: 'Tell someone about a pattern you notice in your dating life' },
  { idx: 161, level: 3, text: 'Share one thing you\'re grieving with a compassionate stranger' },
  { idx: 162, level: 3, text: 'Pretend to be a superhero and vulnerably ask for help' },
  { idx: 163, level: 3, text: 'Practice "exposing your need for approval" to someone' },
  { idx: 164, level: 3, text: 'Tell someone about the "little boy/girl inside you"' },
  { idx: 165, level: 3, text: 'Share what "turn on" means to you with someone' },
  { idx: 166, level: 3, text: 'Practice "triple welcoming" an uncomfortable emotion before approaching' },
  { idx: 167, level: 3, text: 'Ask someone to witness you expressing a difficult emotion' },
  { idx: 168, level: 3, text: 'Share your relationship with your father' },
  { idx: 169, level: 3, text: 'Practice "squeezing solar plexus while saying hi" to feel blocked energy' },
  { idx: 170, level: 3, text: 'Tell someone about a time you felt powerless' },
  { idx: 171, level: 3, text: 'Share one way you\'ve been hurt in relationships' },
  { idx: 172, level: 3, text: 'Practice "humping air with moaning" alone, then talk to someone (tension release)' },
  { idx: 173, level: 3, text: 'Ask someone their biggest relationship fear' },
  { idx: 174, level: 3, text: 'Share what "polarity" means to you' },
  { idx: 175, level: 3, text: 'Practice "I need permission to feel turned on" vs "I don\'t need permission"' },
  { idx: 176, level: 3, text: 'Tell someone about your sexual shame' },
  { idx: 177, level: 3, text: 'Share one way you abandon yourself in relationships' },
  { idx: 178, level: 3, text: 'Practice "gazing while thinking about rejection" at someone' },
  { idx: 179, level: 3, text: 'Tell someone what you\'re most self-conscious about physically' },
  { idx: 180, level: 3, text: 'Share your "existential kink" realization with someone' },
  { idx: 181, level: 3, text: 'Practice "sperm swimming meditation" visualization before approaching' },
  { idx: 182, level: 3, text: 'Ask someone to do a "worst possible approach" exercise with you' },
  { idx: 183, level: 3, text: 'Tell someone about your relationship patterns with women' },
  { idx: 184, level: 3, text: 'Share what "attachment vs aversion" means in your dating life' },
  { idx: 185, level: 3, text: 'Practice "squeezing hips and solar plexus" before approaching' },
  { idx: 186, level: 3, text: 'Tell someone about a time you felt abandoned' },
  { idx: 187, level: 3, text: 'Share your biggest insecurity about sex' },
  { idx: 188, level: 3, text: 'Practice "jaw muscle pressure point gazing" with someone' },
  { idx: 189, level: 3, text: 'Tell someone what you\'re learning about yourself' },
  { idx: 190, level: 3, text: 'Share one way you protect your heart' },
  { idx: 191, level: 3, text: 'Practice "touching exercises" - ask to hold someone\'s hand platonically' },
  { idx: 192, level: 3, text: 'Tell someone about your inner critic\'s favorite insult' },
  { idx: 193, level: 3, text: 'Share what "dominant energy" means to you' },
  { idx: 194, level: 3, text: 'Practice "shaking exercises" for 5 minutes before approaching' },
  { idx: 195, level: 3, text: 'Tell someone about your "mommy and daddy something" wounds' },
  { idx: 196, level: 3, text: 'Share what turns you on (non-physically)' },
  { idx: 197, level: 3, text: 'Practice "wall off exercise" - intentionally close then open in conversation' },
  { idx: 198, level: 3, text: 'Tell someone about your relationship with vulnerability' },
  { idx: 199, level: 3, text: 'Share one thing you\'re working on in personal growth' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEVEL 4: BOLD SOCIAL EXPERIMENTS (idx 200-299, 100 challenges)
  // ═══════════════════════════════════════════════════════════════════════════════
  { idx: 200, level: 4, text: 'Walk around with large map asking for directions to Atlantis' },
  { idx: 201, level: 4, text: 'Set up "Free Air Guitar Lessons" booth' },
  { idx: 202, level: 4, text: 'Pretend you lost your "sense of rhythm" and ask for help finding it' },
  { idx: 203, level: 4, text: 'Sell clouds as a business idea' },
  { idx: 204, level: 4, text: 'Hold fake bake sale with invisible goods described in detail' },
  { idx: 205, level: 4, text: 'Challenge someone to karaoke duet with toy microphone' },
  { idx: 206, level: 4, text: 'Bring giant foam finger cheering for random people' },
  { idx: 207, level: 4, text: 'Be a human mannequin and let strangers pose you' },
  { idx: 208, level: 4, text: 'Start public meditation session sitting cross-legged' },
  { idx: 209, level: 4, text: 'Pretend to be lifeguard patrolling a park' },
  { idx: 210, level: 4, text: 'Walk with clipboard signing people up for absurd reality show' },
  { idx: 211, level: 4, text: 'Create human spotlight following someone with flashlight' },
  { idx: 212, level: 4, text: 'Hold imaginary press conference in park' },
  { idx: 213, level: 4, text: 'Pretend to be talent show judge rating strangers\' walking' },
  { idx: 214, level: 4, text: 'Carry rabbit\'s foot offering good luck rubs' },
  { idx: 215, level: 4, text: 'Ask for autographs insisting people are famous' },
  { idx: 216, level: 4, text: 'Give motivational speech about perfect sandwich making' },
  { idx: 217, level: 4, text: 'Carry empty frame asking people to pose for portrait' },
  { idx: 218, level: 4, text: 'Set up imaginary art gallery with invisible paintings' },
  { idx: 219, level: 4, text: 'Offer free haircuts with imaginary scissors' },
  { idx: 220, level: 4, text: 'Direct pedestrian traffic as fake police officer' },
  { idx: 221, level: 4, text: 'Brainstorm ridiculous inventions like flying toaster' },
  { idx: 222, level: 4, text: 'Run fake science experiment testing invisible particles' },
  { idx: 223, level: 4, text: 'March through space with invisible flag starting parade' },
  { idx: 224, level: 4, text: 'Carry timer challenging people to beat the clock' },
  { idx: 225, level: 4, text: 'Pretend to be possessed asking for exorcism' },
  { idx: 226, level: 4, text: 'Protest with absurd cause like free bubblegum' },
  { idx: 227, level: 4, text: 'Wear full banana suit asking people to peel you' },
  { idx: 228, level: 4, text: 'Have public debate with yourself switching sides' },
  { idx: 229, level: 4, text: 'Host fake talent show recruiting performers' },
  { idx: 230, level: 4, text: 'Use megaphone giving speech about power of socks' },
  { idx: 231, level: 4, text: 'Walk holding full-sized mirror for strangers to admire themselves' },
  { idx: 232, level: 4, text: 'Offer signatures on "save the dinosaurs" petition' },
  { idx: 233, level: 4, text: 'Be drill sergeant commanding strangers to exercise' },
  { idx: 234, level: 4, text: 'Carry bowl of cereal offering bites to strangers' },
  { idx: 235, level: 4, text: 'Audition for musical with spontaneous song and dance' },
  { idx: 236, level: 4, text: 'Carry "THE END IS NIGH" sign warning of fake apocalypse' },
  { idx: 237, level: 4, text: 'Lead conga line seeing how many join' },
  { idx: 238, level: 4, text: 'Ask if anyone\'s seen your pet alligator' },
  { idx: 239, level: 4, text: 'Set up fake presidential campaign with giant poster of yourself' },
  { idx: 240, level: 4, text: 'Dress as royalty demanding people bow' },
  { idx: 241, level: 4, text: 'Shop blindfolded asking strangers for help' },
  { idx: 242, level: 4, text: 'Carry handcuffed briefcase whispering about "the mission"' },
  { idx: 243, level: 4, text: 'Direct traffic with exaggerated gestures' },
  { idx: 244, level: 4, text: 'Challenge strangers to roast battle' },
  { idx: 245, level: 4, text: 'Sign invisible books as famous author' },
  { idx: 246, level: 4, text: 'Take loud absurd phone call about candy stock market' },
  { idx: 247, level: 4, text: 'Challenge to dance battle with your own sound effects' },
  { idx: 248, level: 4, text: 'Have meltdown about losing imaginary best friend' },
  { idx: 249, level: 4, text: 'Carry celebrity cutout insisting on introductions' },
  { idx: 250, level: 4, text: 'Talk into walkie-talkie coordinating secret operation' },
  { idx: 251, level: 4, text: 'Order everything in rhyme at restaurant' },
  { idx: 252, level: 4, text: 'Get fake married with random officiant and spouse' },
  { idx: 253, level: 4, text: 'Sell autographed photos of yourself' },
  { idx: 254, level: 4, text: 'Start group workout session with strangers' },
  { idx: 255, level: 4, text: 'Wear cape reading minds and guessing secrets' },
  { idx: 256, level: 4, text: 'Dress as butler serving random people with tray' },
  { idx: 257, level: 4, text: 'Use megaphone auctioning imaginary products' },
  { idx: 258, level: 4, text: 'Hold press conference answering questions nobody asked' },
  { idx: 259, level: 4, text: 'Survey about absurd topics like animals voting' },
  { idx: 260, level: 4, text: 'March for ridiculous cause chanting slogans' },
  { idx: 261, level: 4, text: 'Perform nonsensical magic tricks as magician' },
  { idx: 262, level: 4, text: 'Dramatically gift flowers to random strangers' },
  { idx: 263, level: 4, text: 'Film fake commercial using people as extras' },
  { idx: 264, level: 4, text: 'Play game show contestant looking for final clue' },
  { idx: 265, level: 4, text: 'Sit at stranger\'s table acting like old friend' },
  { idx: 266, level: 4, text: 'Carry fish bowl asking for name suggestions' },
  { idx: 267, level: 4, text: 'Shout random historical facts as lecture' },
  { idx: 268, level: 4, text: 'Time people crossing street as drill instructor' },
  { idx: 269, level: 4, text: 'Set up "free hugs for robots only" booth' },
  { idx: 270, level: 4, text: 'Offer toy money investments for business ideas' },
  { idx: 271, level: 4, text: 'Teach "Advanced Ninja Studies" mock lecture' },
  { idx: 272, level: 4, text: 'Challenge strangers to duel with inflatable sword' },
  { idx: 273, level: 4, text: 'Take orders as waiter in non-restaurant public space' },
  { idx: 274, level: 4, text: 'Run "complaints desk" accepting absurd complaints' },
  { idx: 275, level: 4, text: 'Wear bathrobe in public acting like hotel lobby' },
  { idx: 276, level: 4, text: 'Narrate people\'s life stories with megaphone' },
  { idx: 277, level: 4, text: 'Search for "invisible pet hamster" asking for help' },
  { idx: 278, level: 4, text: 'Start volleyball game with beach ball' },
  { idx: 279, level: 4, text: 'Measure random objects as scientist' },
  { idx: 280, level: 4, text: 'Search for missing pancake with frying pan' },
  { idx: 281, level: 4, text: 'Conduct imaginary orchestra inviting others' },
  { idx: 282, level: 4, text: 'Offer invisible ice cream cones from "Free Ice Cream" sign' },
  { idx: 283, level: 4, text: 'Practice yoga on busy sidewalk inviting others' },
  { idx: 284, level: 4, text: 'Auction random ground objects with toy megaphone' },
  { idx: 285, level: 4, text: 'Chant "more fries!" in fast-food line' },
  { idx: 286, level: 4, text: 'Officiate people\'s movements as referee' },
  { idx: 287, level: 4, text: 'Make loud fake phone calls in imaginary booth' },
  { idx: 288, level: 4, text: 'Ask store to gift-wrap giant empty box' },
  { idx: 289, level: 4, text: 'Give strangers pep talks as motivational coach' },
  { idx: 290, level: 4, text: 'Sell invisible lemonade from rare lemons' },
  { idx: 291, level: 4, text: 'Type loudly in coffee shop asking for literary advice' },
  { idx: 292, level: 4, text: 'Chase invisible butterflies with giant net' },
  { idx: 293, level: 4, text: 'Search for buried treasure as pirate' },
  { idx: 294, level: 4, text: 'Act as time traveler surprised by current year' },
  { idx: 295, level: 4, text: 'Ask stores if they sell time machines or unicorn food' },
  { idx: 296, level: 4, text: 'Be random person\'s private security' },
  { idx: 297, level: 4, text: 'Bring outside restaurant food, order only water' },
  { idx: 298, level: 4, text: 'Do evil villain laugh in crowded area' },
  { idx: 299, level: 4, text: 'Practice "conscious welcoming gazing" with strangers' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEVEL 5: TENSION & ESCALATION (idx 300-399, 100 challenges)
  // Real-World Applied Tension & Embodied Presence Challenges
  // ═══════════════════════════════════════════════════════════════════════════════
  { idx: 300, level: 5, text: 'The 20-Second Silence: Hold eye contact for 20s without speaking, then say "I had to come say hi." Do 3 times.' },
  { idx: 301, level: 5, text: 'Mid-Sentence Freeze: Freeze mid-sentence for 5s while maintaining eye contact. Continue naturally. Repeat 5 times.' },
  { idx: 302, level: 5, text: 'Squeeze-Release Approach: Squeeze torso while walking up. Release when saying "hi." Do 10 times.' },
  { idx: 303, level: 5, text: 'Compliment + Extended Gaze: Give compliment, hold eye contact for 7s after they respond. Do 5 times.' },
  { idx: 304, level: 5, text: 'Silent "Hi" Approach: Make eye contact, pause 5s, say "hi", pause 3s more. Let them respond first. Repeat 5 times.' },
  { idx: 305, level: 5, text: 'Barista Number Close: Ask barista for their number with steady eye contact. Do at 3 different coffee shops.' },
  { idx: 306, level: 5, text: 'Energy Compliment: Tell someone "You have really magnetic energy" while holding eye contact. Do 5 times.' },
  { idx: 307, level: 5, text: 'The Self-Check Approach: Check "Do I like them or want validation?" Only approach if genuinely drawn. Do 10 times.' },
  { idx: 308, level: 5, text: '"Are You Happy?" Question: After 2 min small talk, ask "Are you happy?" Hold space for answer. Do 3 times.' },
  { idx: 309, level: 5, text: 'Heart-Forward Walk: Walk 15 min with chest leading. Approach 5 people from this posture.' },
  { idx: 310, level: 5, text: 'Direct Attraction Statement: Tell someone "I find you attractive and wanted to meet you" within 30s. Do 5 times.' },
  { idx: 311, level: 5, text: 'Eyes-to-Heart Connection: Consciously connect from eyes through heart. Maintain for 5-min conversation. Repeat 3 times.' },
  { idx: 312, level: 5, text: 'Bold Curiosity: Ask 5 different people "Are you single?" early in conversation with genuine curiosity.' },
  { idx: 313, level: 5, text: 'Date Request With Eye Contact: Ask on a date with unbroken eye contact from question to full response. Do 3 times.' },
  { idx: 314, level: 5, text: 'Standing Still Gaze: Begin talking, stop moving completely, gaze for 10s mid-conversation. Do 3 times.' },
  { idx: 315, level: 5, text: '"Being Present" Admission: Tell someone "I\'m working on being more present" and ask what helps them. Do 5 times.' },
  { idx: 316, level: 5, text: '"What Do You Want?" Hold: Ask "What do you really want in life?" Maintain eye contact through entire answer. Do 3 times.' },
  { idx: 317, level: 5, text: 'Grounded Silence Holding: When tension arises, plant feet and breathe deeply for 10s instead of filling space. Do 5 times.' },
  { idx: 318, level: 5, text: '10-Second Breathing Approach: Walk up, make eye contact, breathe together 10s before speaking. Do 3 times.' },
  { idx: 319, level: 5, text: 'Unexpected Dance Request: Ask "Would you slow dance with me right here for 30s?" in grocery store. Do 3 times.' },
  { idx: 320, level: 5, text: 'Hand-Hold Grounding: Ask "Can I hold your hand for a moment?" Hold silently for 30s. Do 2 times.' },
  { idx: 321, level: 5, text: '"You\'re Beautiful" + Silence: Tell someone "You\'re beautiful" then don\'t say anything for 10s. Do 5 times.' },
  { idx: 322, level: 5, text: 'Playful Rating Request: Ask "On a scale of 1-10, how would you rate this approach?" with playful energy. Do 3 times.' },
  { idx: 323, level: 5, text: 'Head vs Heart Banter: Have 2 conversations from "head" (clever), then 2 from "heart" (warm). Notice difference.' },
  { idx: 324, level: 5, text: 'Extended Handshake: Hold handshake 5s longer than normal while maintaining eye contact. Do 10 times.' },
  { idx: 325, level: 5, text: 'Direct Interest Statement: Tell someone "I want to get to know you" with full presence. Do 5 times.' },
  { idx: 326, level: 5, text: 'Wordless Connection: Make eye contact across room for 30s. Then approach and say "I felt that." Do 3 times.' },
  { idx: 327, level: 5, text: 'Palm Reading Touch: Offer palm reading. Hold hand, look at it, look up, hold eye contact 10s. Do 5 times.' },
  { idx: 328, level: 5, text: 'Direct Desire Question: Ask "What turns you on?" with genuine curiosity in appropriate setting. Do 2 times.' },
  { idx: 329, level: 5, text: 'Power Center Squeeze: While talking to someone attractive, squeeze lower belly and speak from there. Do 5 times.' },
  { idx: 330, level: 5, text: 'Fantasy Share: Share a non-sexual fantasy with full vulnerability in intimate conversation. Do 2 times.' },
  { idx: 331, level: 5, text: 'Forward-Back Connection Walk: Take step backward, maintain eye contact, step forward. Do 3 times in one conversation.' },
  { idx: 332, level: 5, text: 'Tension Acknowledgment: Ask "Do you feel this tension between us?" and don\'t laugh it off. Do 3 times.' },
  { idx: 333, level: 5, text: 'Intentional Rejection Practice: Approach 5 people trying to get rejected. Make it deliberately bold. Notice freedom.' },
  { idx: 334, level: 5, text: 'Sexual Development Share: Tell someone "I\'m working on being more comfortable with my sexuality." Do 2 times.' },
  { idx: 335, level: 5, text: 'Revealing Exercise Request: Ask "Share something vulnerable? I\'ll go first." Then share something real. Do 3 times.' },
  { idx: 336, level: 5, text: 'Banter Muscle Building: Have 5 conversations with at least 3 playful teases per conversation.' },
  { idx: 337, level: 5, text: 'Energy Acknowledgment: Tell someone "You have incredible energy" and when they deflect, insist while maintaining eye contact. Do 5 times.' },
  { idx: 338, level: 5, text: 'Intimacy Question: Ask "What\'s your relationship with intimacy like?" Hold space for deep answer. Do 2 times.' },
  { idx: 339, level: 5, text: 'Rooted Stance Practice: Plant feet shoulder-width apart, imagine roots growing down. Approach and maintain groundedness. Do 10 times.' },
  { idx: 340, level: 5, text: '"Learning to Stay Open" Share: Tell someone "I\'m learning to stay open even when I feel scared." Do 3 times.' },
  { idx: 341, level: 5, text: 'Playful Slap Game: Initiate hand-slap game while keeping eye contact with someone you\'re vibing with. Do 2 times.' },
  { idx: 342, level: 5, text: 'Teach Grounding: Show someone how to feel grounded - plant feet and breathe deeply together. Do 2 times.' },
  { idx: 343, level: 5, text: 'Attachment Style Discussion: Share your attachment style and ask about theirs in deeper conversation. Do 2 times.' },
  { idx: 344, level: 5, text: 'Authority Figure Approach: Ask a police officer, security guard, or authority figure on a date. Do 1 time.' },
  { idx: 345, level: 5, text: 'Gym Approach: Ask someone out while they\'re working out at the gym between sets. Do 2 times.' },
  { idx: 346, level: 5, text: 'Server Number Request: Ask your waiter/waitress for their number at the end of the meal. Do 3 times.' },
  { idx: 347, level: 5, text: 'Retail Employee Date Request: Ask retail employee if they\'d like coffee after their shift. Do 3 times.' },
  { idx: 348, level: 5, text: 'Heavy Step Walking: Walk toward someone with deliberately heavy, grounded steps. Notice energy shift. Do 10 times.' },
  { idx: 349, level: 5, text: 'Energy Attraction Statement: Tell someone "I\'m really attracted to your energy" early in conversation. Do 5 times.' },
  { idx: 350, level: 5, text: 'Authority Reversal: Ask someone who has authority in a situation (manager, supervisor) out on a date. Do 2 times.' },
  { idx: 351, level: 5, text: 'Flight Attendant Approach: Strike up conversation with flight attendant and ask for number before deplaning. Do 1 time.' },
  { idx: 352, level: 5, text: 'Rideshare Driver Connect: Have deep conversation with Uber/Lyft driver and ask to stay in touch. Do 3 times.' },
  { idx: 353, level: 5, text: 'Magnetic Feet Visualization: Imagine feet are magnetic and stuck to ground. Walk slowly and deliberately. Do 10 times.' },
  { idx: 354, level: 5, text: 'Adventure Invitation: Tell someone "I\'d like to take you on an adventure." Say "Trust me and find out." Do 3 times.' },
  { idx: 355, level: 5, text: 'Extended Gaze Request: Ask "Can we just look at each other for a minute without talking?" Then do it. Do 2 times.' },
  { idx: 356, level: 5, text: 'Breath-Synchronized Exit: Take deep breath together, exhale slowly while holding eye contact, then say goodbye. Do 5 times.' },
  { idx: 357, level: 5, text: 'Existential Kink Mention: Explain "existential kink" concept with open-minded person. Do 1 time.' },
  { idx: 358, level: 5, text: 'Turn-On Question: Ask "What\'s your biggest turn-on?" in appropriate intimate setting. Do 2 times.' },
  { idx: 359, level: 5, text: 'Body Sensation Narration: Share what you\'re feeling in your body: "I notice my heart beating faster right now." Do 3 times.' },
  { idx: 360, level: 5, text: 'Sexual Shame Acknowledgment: Share "I\'m working on some sexual shame I have" with someone you trust. Do 1 time.' },
  { idx: 361, level: 5, text: 'Heart Opening Request: Ask "Can we do something vulnerable? Just look at each other and breathe for a bit?" Do 2 times.' },
  { idx: 362, level: 5, text: 'Hip Rotation Presence: Subtly rotate hips while holding eye contact. Notice how it affects vibe. Do 5 times.' },
  { idx: 363, level: 5, text: 'Magnetic Presence Feedback: Tell someone "There\'s something magnetic about your presence" and elaborate. Do 5 times.' },
  { idx: 364, level: 5, text: 'Banter From Heart: Have playful conversation where every tease comes from warmth, not cleverness. Do 5 times.' },
  { idx: 365, level: 5, text: 'Own Your Feelings: State "I\'m feeling nervous/excited/turned on right now" without apologizing. Do 5 times.' },
  { idx: 366, level: 5, text: 'Polarity Discussion: Ask what they think about "masculine and feminine energy" and share your thoughts. Do 2 times.' },
  { idx: 367, level: 5, text: 'Aliveness Question: Ask "What makes you feel most alive?" Really listen. Share yours. Do 5 times.' },
  { idx: 368, level: 5, text: 'Librarian Approach: Strike up conversation with librarian, find common ground, ask them out. Do 2 times.' },
  { idx: 369, level: 5, text: 'Grounded Roots Gaze: Imagine roots from feet while talking to someone attractive. Maintain through conversation. Do 5 times.' },
  { idx: 370, level: 5, text: 'Heart Opening Statement: Tell someone "I\'m practicing opening my heart more" and watch vulnerability create connection. Do 3 times.' },
  { idx: 371, level: 5, text: 'Vulnerable Number Exchange: Say "I\'d really like to stay in touch. Can I get your number?" with full sincerity. Do 5 times.' },
  { idx: 372, level: 5, text: 'Neural Pathway Awareness: Imagine old fear pathways breaking apart before approaching someone intimidating. Do 5 times.' },
  { idx: 373, level: 5, text: 'Releasing Wanting Share: Tell someone "I\'m working on releasing attachment to outcomes" in conversation. Do 2 times.' },
  { idx: 374, level: 5, text: 'Curiosity Definition Request: Ask "What does genuine curiosity feel like to you?" Share your experience. Do 3 times.' },
  { idx: 375, level: 5, text: 'Spontaneous Dance Move: Ask someone to slow dance right there in moment (coffee shop, park). Do 2 times.' },
  { idx: 376, level: 5, text: 'Bold Banter Challenge: Banter until someone gets faux-offended, hold tension without apologizing. Do 3 times.' },
  { idx: 377, level: 5, text: 'Captivating Acknowledgment: Tell someone "I find your presence captivating" and specify what captivates you. Do 5 times.' },
  { idx: 378, level: 5, text: 'Touch Exercise Proposal: Ask "Can we try a grounding exercise? Just holding hands for a moment?" Do 2 times.' },
  { idx: 379, level: 5, text: 'Approach Intention Check: Before every approach, ask "Why am I really approaching?" Adjust if validation-seeking. Do 20 times.' },
  { idx: 380, level: 5, text: 'Vulnerability Journey Share: Share your "journey with vulnerability" - what you\'re learning, what\'s hard. Do 2 times.' },
  { idx: 381, level: 5, text: 'Sexuality Conversation: Ask about their relationship with their own sexuality. Share yours. Do 1 time.' },
  { idx: 382, level: 5, text: 'Curiosity Cultivation: Approach 10 people in one day from pure curiosity about who they are, not what you can get.' },
  { idx: 383, level: 5, text: 'Authenticity Attraction: Tell someone "I\'m attracted to how authentic you are" and give an example. Do 3 times.' },
  { idx: 384, level: 5, text: 'Turn-On Block Discussion: Discuss what blocks you from feeling turned on in life with someone open. Do 1 time.' },
  { idx: 385, level: 5, text: 'Giving Without Taking: Have 5 conversations where you give compliments, attention, energy without expecting anything back.' },
  { idx: 386, level: 5, text: 'Pattern Sharing: Tell someone "I\'m noticing a pattern I do in dating" and share vulnerably. Do 2 times.' },
  { idx: 387, level: 5, text: 'Polarity Question: Ask "What do you think about the idea that we all have masculine and feminine energy?" Do 3 times.' },
  { idx: 388, level: 5, text: 'Arm Restraint Presence: Cross arms briefly, then uncross and open your body. Notice energy shift. Do 5 times.' },
  { idx: 389, level: 5, text: 'Tension Presence Statement: Tell someone "I\'m working on staying present when I feel tension instead of running." Do 2 times.' },
  { idx: 390, level: 5, text: 'Intimacy Definition: Ask "What does emotional intimacy mean to you?" Share your definition. Do 3 times.' },
  { idx: 391, level: 5, text: 'Dance Floor Presence: Go to place with music and dance fully present for 30 min, making eye contact. Do 1 time.' },
  { idx: 392, level: 5, text: 'Inner Work Mention: Tell someone "I\'ve been doing a lot of inner work lately" and share one thing learned. Do 3 times.' },
  { idx: 393, level: 5, text: 'Wall-Off Awareness: Notice when you "wall off" (close body language, stop feeling). Deliberately re-open. Do 5 times.' },
  { idx: 394, level: 5, text: 'Walling Off Question: Ask "Do you notice yourself emotionally shutting down? What brings that up?" Do 2 times.' },
  { idx: 395, level: 5, text: '30-Second Unbroken Gaze: Hold eye contact for 30+ seconds without breaking or laughing. Let intensity build. Do 3 times.' },
  { idx: 396, level: 5, text: 'Embodied Presence Share: Tell someone "I\'m learning about embodied presence - being fully in my body while connecting." Do 2 times.' },
  { idx: 397, level: 5, text: 'Passion Question: In appropriate intimate context, ask "What are you most passionate about sexually?" Do 1 time.' },
  { idx: 398, level: 5, text: 'Extended Silence Hold: During conversation, let silence build for 45 seconds without filling it. Breathe, stay present. Do 2 times.' },
  { idx: 399, level: 5, text: 'Deep Attraction Statement: Tell someone "I find you deeply attractive - not just physically, but energetically" and elaborate. Do 3 times.' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEVEL 6: EMBODIED APPROACH FOUNDATIONS (idx 400-499, 100 challenges)
  // ═══════════════════════════════════════════════════════════════════════════════
  { idx: 400, level: 6, text: 'Jaw-Relaxed Approaches: Approach 10 people with completely relaxed jaw and tongue. Notice how it affects voice.' },
  { idx: 401, level: 6, text: 'Belly-Breathing Conversations: Hold 5 conversations breathing only from belly. Speak on exhale. Notice presence difference.' },
  { idx: 402, level: 6, text: 'Squeeze-Release Walk-Ups: Squeeze solar plexus while walking toward someone. Release when saying "hi." Do 10 times.' },
  { idx: 403, level: 6, text: 'Heart-Led Quinta Walks: Walk through busy area leading from heart for 20 min. Approach 3 people from this posture.' },
  { idx: 404, level: 6, text: 'Grounding Root Approaches: Imagine roots from feet for 30s before approaching. Approach while maintaining feeling. Repeat 5 times.' },
  { idx: 405, level: 6, text: 'Hip-Squeezing Tension Release: Squeeze hips while approaching. Hold eye contact, release squeeze as you speak. Notice shift.' },
  { idx: 406, level: 6, text: 'Sensation Narration Walk: Quietly narrate what you\'re feeling in body out loud. Approach someone and share one sensation.' },
  { idx: 407, level: 6, text: 'Power Center Activation: Place attention on lower belly. Approach 5 people while breathing into this area. Notice groundedness.' },
  { idx: 408, level: 6, text: 'Feet-As-Magnets Challenge: Imagine feet magnetized to ground. Walk heavily and deliberately to someone. Introduce yourself.' },
  { idx: 409, level: 6, text: 'Shoulder-Down Approaches: Roll shoulders back and down before each approach. Keep relaxed while talking to 10 people.' },
  { idx: 410, level: 6, text: 'Mother Pattern Awareness: After talking to someone attractive, journal 2 min about how interaction mirrored relationship with mother.' },
  { idx: 411, level: 6, text: 'Father Pattern Recognition: Approach authority figure. Afterward, journal about approval-seeking patterns connected to father.' },
  { idx: 412, level: 6, text: '"I\'m Nervous" Admission: Approach 3 attractive people and openly admit "I\'m feeling nervous right now." Hold tension.' },
  { idx: 413, level: 6, text: 'Worthlessness Welcome: Before approaching someone intimidating, welcome feelings of worthlessness for 1 min. Then approach. Repeat 3 times.' },
  { idx: 414, level: 6, text: 'Insecurity Joke Challenge: Make genuine joke about one of your real insecurities to 5 people. Notice relief from not hiding.' },
  { idx: 415, level: 6, text: 'Rejection Story Sharing: Tell 3 strangers about recent rejection. Make it vulnerable, not funny. See how they respond.' },
  { idx: 416, level: 6, text: '"Do I Like Her?" Awareness: During 5 conversations, continuously check "Do I like her or want her to like me?" Notice difference.' },
  { idx: 417, level: 6, text: 'Permission Polarity Test: Approach thinking "I need permission to feel turned on." Then approach without needing permission. Notice difference.' },
  { idx: 418, level: 6, text: 'Attachment Pattern Call-Out: After good conversation, notice if you feel attached to outcome. Text friend describing attachment.' },
  { idx: 419, level: 6, text: 'Aversion Pattern Spotting: Notice when you feel aversion (pulling away, wanting to leave). Stay 2 more minutes anyway. Do 5 times.' },
  { idx: 420, level: 6, text: 'Triple Welcoming Approach: Before approaching, welcome attachment, aversion, and identity ("I\'m not good enough"). Then approach.' },
  { idx: 421, level: 6, text: 'Inner Critic Exposure: After rejection or weird look, stop and speak out loud what inner critic is saying. Do 3 times.' },
  { idx: 422, level: 6, text: 'Mom/Dad Approval Check: During 5 approaches, ask "Am I trying to get their approval like mom/dad\'s?" Adjust energy.' },
  { idx: 423, level: 6, text: 'Shame Story Sharing: Share something you feel sexual shame about with trusted person during coffee. Notice relief.' },
  { idx: 424, level: 6, text: '"What Am I Walling Off?" Check-In: After approach that feels closed, ask "What am I walling off?" Write answer.' },
  { idx: 425, level: 6, text: '"I\'m a Sexual Being" Affirmation Walk: Walk through public space 10 min repeating internally. Notice posture/eye contact change.' },
  { idx: 426, level: 6, text: 'Turn-On Without Permission: Approach 5 people while allowing yourself to feel turned on without needing their permission. Notice shift.' },
  { idx: 427, level: 6, text: 'Existential Kink Micro-Dose: Find rejection or uncomfortable moment. Welcome it and notice any "pleasure" in discomfort. Repeat 5 times.' },
  { idx: 428, level: 6, text: 'Hip Movement Integration: Do 20 hip circles in public bathroom. Immediately approach someone. Notice if energy feels more alive.' },
  { idx: 429, level: 6, text: 'Moaning Practice Then Approach: In car, practice moaning/expressing sensation 2 min. Immediately approach someone. Notice opened energy.' },
  { idx: 430, level: 6, text: 'Sexual Compliment (Appropriate): Give 3 people compliments with subtle sexual undertones (energy-based, not physical).' },
  { idx: 431, level: 6, text: '"Sex is Innocent" Reminder: Before approaching, remind yourself "sex is inherently innocent." Approach from this frame. Repeat 5 times.' },
  { idx: 432, level: 6, text: 'Desire Admission (Contextual): In appropriate setting, tell someone "I find you really attractive" and hold tension without apologizing.' },
  { idx: 433, level: 6, text: 'Polarity Practice: Approach someone and consciously hold "dominant energy" (grounded, directive, present). Notice if they soften. Do 5 times.' },
  { idx: 434, level: 6, text: 'Fantasy Activation (Internal): While talking, briefly imagine what intimacy might be like. Notice how it changes presence. Stay present.' },
  { idx: 435, level: 6, text: 'Voice From Genitals: Practice speaking from pelvic floor (imagine voice originating there). Have 3 conversations this way. Notice shift.' },
  { idx: 436, level: 6, text: 'Sperm Swimming Visualization: Before approaching, visualize sperm swimming upstream (energetically moving from genitals up through body).' },
  { idx: 437, level: 6, text: 'Shoulder-Chest-Pelvis Alignment: Stand with shoulders back, chest open, pelvis slightly forward. Approach 5 people from this posture.' },
  { idx: 438, level: 6, text: '"I Want You" Energy (Non-Verbal): Hold eye contact while internally feeling "I want you" without saying it. Hold 10s. Notice response.' },
  { idx: 439, level: 6, text: 'Breathwork Before Approach: Do 10 deep belly breaths before approaching someone intimidating. Notice calm power.' },
  { idx: 440, level: 6, text: '20-Second Silence Hold: During conversation, let silence happen for 20 full seconds. Maintain eye contact and open body. Do 3 times.' },
  { idx: 441, level: 6, text: '"Are You?" Exercise: Ask "Are you happy?" or "Are you free?" Then don\'t say anything else. Hold space for whatever comes.' },
  { idx: 442, level: 6, text: 'No Questions Rule: Have 10-min conversation using ONLY statements, no questions. Forces expression vs extraction. Do 3 times.' },
  { idx: 443, level: 6, text: 'Triggering Person Approach: Identify person who triggers you most (intimidates, attracts, annoys). Approach them. Repeat at 3 locations.' },
  { idx: 444, level: 6, text: 'Hand-Holding Grounding: In appropriate context, ask if you can hold their hand "for grounding exercise." Notice intimacy of simple touch.' },
  { idx: 445, level: 6, text: 'Eye-Reading Emotions: Hold eye contact and try to "read" their emotional state through eyes. Share what you sense. Do 3 times.' },
  { idx: 446, level: 6, text: 'Walking Backward Approach: Walk backward toward someone (safely), then turn and approach normally. Disorientation forces presence. Do 5 times.' },
  { idx: 447, level: 6, text: 'Conscious Closing Then Opening: Intentionally close body language for 30s. Then consciously open it. Notice their response shift.' },
  { idx: 448, level: 6, text: 'Dominant Energy Walk-Up: Walk up with deliberate, slow, grounded steps (not aggressive, just present). Notice dynamic change. Repeat 5 times.' },
  { idx: 449, level: 6, text: 'Heart vs Head Banter Test: During 3 conversations, alternate between "head" banter (witty) and "heart" banter (warm). Notice which feels better.' },
  { idx: 450, level: 6, text: 'Power Center Squeeze: During conversation with someone attractive, squeeze lower abs. Hold while maintaining conversation. Notice groundedness.' },
  { idx: 451, level: 6, text: 'Feet Root While Flirting: While flirting or in tension, imagine feet growing roots. Notice how it prevents "chasing" energy.' },
  { idx: 452, level: 6, text: 'Chest-Led Turn-On: Place attention on chest/heart. Approach while breathing into chest and feeling turned on from there. Notice difference.' },
  { idx: 453, level: 6, text: 'Tension Without Resolution: Create playful tension (tease, flirt, challenge) then DON\'T resolve with laugh or explanation. Let it hang. Do 5 times.' },
  { idx: 454, level: 6, text: '"I Don\'t Need Anything From You" Energy: Approach while truly feeling "I don\'t need anything, I\'m just here." Notice freedom and response.' },
  { idx: 455, level: 6, text: 'Whole Body Yes/No: Before saying yes or no, check your whole body. Does gut, chest, and head all agree? Practice on 5 decisions.' },
  { idx: 456, level: 6, text: 'Authentic "No" Practice: Tell someone "no" to a request and feel solid without over-explaining. Notice power. Do 3 times.' },
  { idx: 457, level: 6, text: '"I Mean Business" Approach: Approach with clear intent - no hiding, no playing small. Say what you want directly. "I\'d like to take you out." Repeat 3 times.' },
  { idx: 458, level: 6, text: 'Sharing Sexual Preferences: In appropriate intimate conversation, share something you actually like sexually. Notice vulnerability and turn-on.' },
  { idx: 459, level: 6, text: 'Last Sexual Experience Share: With someone you trust, share vulnerably about last sexual experience - feelings, fears, enjoyment. Notice intimacy.' },
  { idx: 460, level: 6, text: 'Compliment + Sexual Tension: Give genuine compliment, hold eye contact 5 extra seconds to create sexual tension. Don\'t apologize. Do 5 times.' },
  { idx: 461, level: 6, text: 'Helping Others Feel: When someone shares emotional, don\'t fix it. Hold space and say "I can feel that with you." Practice 3 times.' },
  { idx: 462, level: 6, text: 'Attachment vs Aversion Conversation: Have 20-min conversation noticing every moment of attachment or aversion. Stay present anyway.' },
  { idx: 463, level: 6, text: 'Sensation Description Challenge: During tension moment, describe out loud what you\'re feeling in body. Repeat 3 times.' },
  { idx: 464, level: 6, text: 'Judgment Release Approach: Approach while noticing all judgments about them and yourself. Approach anyway without trying to change judgments.' },
  { idx: 465, level: 6, text: '"Feeling Tension" Admission: During tense moment, say "I\'m feeling tension right now" and don\'t try to resolve it. Just acknowledge. Do 3 times.' },
  { idx: 466, level: 6, text: 'Heart-Only Approach Challenge: Approach 5 people in one day where ONLY intention is heart-to-heart connection, zero agenda for outcome.' },
  { idx: 467, level: 6, text: 'Vulnerable Approach: Tell 3 different people something vulnerable within first minute of conversation. Notice connection depth.' },
  { idx: 468, level: 6, text: 'Rejection Celebration: After being rejected, do a small celebration (fist pump, dance move). Train brain to celebrate courage. Do 5 times.' },
  { idx: 469, level: 6, text: 'Shame Release Yell: In private space, yell out something you\'re ashamed of. Then approach someone. Notice lightness. Do 3 times.' },
  { idx: 470, level: 6, text: 'Body Scan Before Approach: Do 30-second body scan (head to toe awareness) before approaching intimidating person. Repeat 5 times.' },
  { idx: 471, level: 6, text: 'Voice Dropping: Consciously speak from lower register during 5 conversations. Notice how it grounds you and affects others.' },
  { idx: 472, level: 6, text: 'Slow Speech Practice: Speak deliberately slowly during 3 conversations. Notice how it creates presence and gives you thinking space.' },
  { idx: 473, level: 6, text: 'Breath Matching: Match your breathing to someone else\'s for 2 minutes during conversation. Notice energetic sync. Do 3 times.' },
  { idx: 474, level: 6, text: 'Posture Mirror Test: Adopt exact same posture as person you\'re talking to for 5 minutes. Then shift to your natural posture. Notice rapport changes.' },
  { idx: 475, level: 6, text: 'Energy Level Match: Approach someone high-energy with high energy, someone calm with calm energy. Notice ease of connection. Do 5 times.' },
  { idx: 476, level: 6, text: 'Compliment + Silence: Give genuine compliment and just remain silent for 20 seconds afterward. No elaboration. Do 5 times.' },
  { idx: 477, level: 6, text: 'Direct "No" Acceptance: When someone says no or seems uninterested, say "I appreciate your honesty" and walk away with dignity. Do 5 times.' },
  { idx: 478, level: 6, text: 'Outcome Release Mantra: Before 10 approaches, say "I release attachment to outcome" and genuinely feel it. Notice freedom.' },
  { idx: 479, level: 6, text: 'Gratitude Expression: After every conversation (good or bad), internally say "thank you for that experience." Do this 20 times.' },
  { idx: 480, level: 6, text: 'Fear Inventory: List 5 specific fears about approaching. Then approach 5 people, noticing which fears actually manifest (usually none).' },
  { idx: 481, level: 6, text: 'Worst Case Scenario: Before scary approach, imagine worst realistic outcome. Realize it\'s survivable. Then approach anyway. Do 5 times.' },
  { idx: 482, level: 6, text: 'Best Case Visualization: Before approach, vividly imagine best possible outcome for 30 seconds. Then approach from that energy. Do 5 times.' },
  { idx: 483, level: 6, text: 'Neutral Approach: Approach 10 people with zero expectation of good or bad outcome. Just pure curiosity about what will happen.' },
  { idx: 484, level: 6, text: 'Speed Approach Challenge: Approach 10 people in 10 minutes. No time to overthink. Notice how action creates momentum.' },
  { idx: 485, level: 6, text: 'Quality Over Quantity: Have one 30-minute deep conversation with a stranger. Notice how different it feels from quick approaches.' },
  { idx: 486, level: 6, text: 'Same Person Return: Return to someone you talked to earlier and continue the conversation. "Hey, I realized I wanted to keep talking." Do 3 times.' },
  { idx: 487, level: 6, text: 'Group Approach: Approach a group of 3+ people and engage with all of them. Notice how it builds social confidence. Do 5 times.' },
  { idx: 488, level: 6, text: 'Mixed Group Navigation: Approach a mixed gender group and engage both men and women equally. Notice social dynamics. Do 3 times.' },
  { idx: 489, level: 6, text: 'Couple Approach: Approach a couple and have a genuine conversation with both. Notice how it removes sexual pressure. Do 3 times.' },
  { idx: 490, level: 6, text: 'Elderly Person Connection: Have a 15-minute conversation with someone over 65. Notice wisdom and different perspective. Do 2 times.' },
  { idx: 491, level: 6, text: 'Child Interaction (with parent present): Interact playfully with a child while parent is present. Notice innocence and joy. Do 3 times.' },
  { idx: 492, level: 6, text: 'Service Worker Appreciation: Have genuine 5-minute conversation with service worker (barista, cashier) not just transactional. Do 5 times.' },
  { idx: 493, level: 6, text: 'Language Barrier Connection: Approach someone who speaks a different language. Connect through body language and emotion. Do 2 times.' },
  { idx: 494, level: 6, text: 'Different Culture Approach: Approach someone from visibly different cultural background. Ask about their culture with genuine curiosity. Do 3 times.' },
  { idx: 495, level: 6, text: 'Subculture Exploration: Approach someone from a subculture you don\'t understand (punk, goth, etc). Learn about their world. Do 2 times.' },
  { idx: 496, level: 6, text: 'Opposite Political View: Have calm conversation with someone who likely has opposite political views. Focus on understanding. Do 1 time.' },
  { idx: 497, level: 6, text: 'Religious Difference: Talk to someone of different faith about their beliefs with genuine curiosity, not debate. Do 1 time.' },
  { idx: 498, level: 6, text: 'Generational Gap: Have conversation with someone 20+ years older or younger about how they see the world differently. Do 2 times.' },
  { idx: 499, level: 6, text: 'Disability Awareness: Approach and have normal conversation with someone with visible disability. Notice any discomfort in yourself. Do 1 time.' },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEVEL 7: DEEP INTEGRATION & MASTERY (idx 500-566, 67 challenges)
  // ═══════════════════════════════════════════════════════════════════════════════
  { idx: 500, level: 7, text: 'Economic Gap Bridge: Talk to someone clearly from different economic class. Notice assumptions and prejudices in yourself. Do 2 times.' },
  { idx: 501, level: 7, text: 'Homeless Connection: Have 10-minute genuine conversation with homeless person. Buy them food and listen to their story. Do 1 time.' },
  { idx: 502, level: 7, text: 'CEO/Executive Approach: Approach someone in obvious position of power. Notice your reactions and theirs. Do 2 times.' },
  { idx: 503, level: 7, text: 'Artist/Creative: Have conversation with street performer or artist about their craft and why they do it. Do 2 times.' },
  { idx: 504, level: 7, text: 'Solo Diner: Sit with someone eating alone and ask to join them. If they say yes, have genuine meal together. Do 3 times.' },
  { idx: 505, level: 7, text: 'Park Bench Stranger: Sit on bench next to stranger and start conversation about what they\'re observing. Do 5 times.' },
  { idx: 506, level: 7, text: 'Bookstore Connection: Approach someone in bookstore and discuss what they\'re reading. Recommend a book to each other. Do 3 times.' },
  { idx: 507, level: 7, text: 'Museum/Gallery: Start conversation with someone at museum/gallery about a piece of art you\'re both viewing. Do 2 times.' },
  { idx: 508, level: 7, text: 'Coffee Shop Regular: Become a regular at a coffee shop and build genuine relationship with 3 different regulars over time.' },
  { idx: 509, level: 7, text: 'Dog Park Connection: Use dogs as connection point but go deeper than surface talk. Learn their story. Do 3 times.' },
  { idx: 510, level: 7, text: 'Gym Accountability: Approach someone at gym and ask to be accountability partners. Exchange numbers for progress check-ins. Do 1 time.' },
  { idx: 511, level: 7, text: 'Yoga/Fitness Class: Introduce yourself to someone before or after class. Suggest grabbing smoothie after. Do 3 times.' },
  { idx: 512, level: 7, text: 'Sports Watching: Approach someone watching sports (at bar, event). Bond over game then transition to personal topics. Do 2 times.' },
  { idx: 513, level: 7, text: 'Concert/Event: Strike up conversation during intermission or before show. Trade contact info to meet up at future events. Do 2 times.' },
  { idx: 514, level: 7, text: 'Protest/Rally: Attend public event and connect with someone over shared values. Go deeper than surface activism. Do 1 time.' },
  { idx: 515, level: 7, text: 'Volunteer Together: Volunteer somewhere and use shared activity to build genuine connection with fellow volunteer. Do 1 time.' },
  { idx: 516, level: 7, text: 'Class/Workshop: Take class on something new. Connect with classmate over shared learning experience. Do 1 time.' },
  { idx: 517, level: 7, text: 'Meetup Group: Attend meetup for hobby/interest. Organize smaller hangout with 2-3 people from group afterward. Do 1 time.' },
  { idx: 518, level: 7, text: 'Public Transit Regular: Strike up conversation with someone on your regular commute route. Build familiarity over time. Do 5 times.' },
  { idx: 519, level: 7, text: 'Neighbor Introduction: Introduce yourself to 5 neighbors you haven\'t met yet. Have 10-minute conversations with each.' },
  { idx: 520, level: 7, text: 'Local Business Owner: Get to know owner of local business. Ask about their journey and challenges. Become supporter. Do 2 times.' },
  { idx: 521, level: 7, text: 'Teacher/Mentor: Approach someone who knows something you want to learn. Ask if they\'d teach you basics. Offer value exchange. Do 1 time.' },
  { idx: 522, level: 7, text: 'Reverse Mentorship: Find someone younger/less experienced in your area of expertise. Offer to mentor them. Do 1 time.' },
  { idx: 523, level: 7, text: 'Skill Trade: Find someone with complementary skill. Propose skill trade arrangement (you teach X, they teach Y). Do 1 time.' },
  { idx: 524, level: 7, text: 'Adventure Buddy: Find someone who wants to try same new activity. Plan outing together (hiking, escape room, etc). Do 1 time.' },
  { idx: 525, level: 7, text: 'Food Tour: Invite stranger to explore new restaurant/food truck with you. Split dishes and share culinary adventure. Do 2 times.' },
  { idx: 526, level: 7, text: 'Photo Walk: Invite someone to walk around city taking photos together. No phones except for photos. Do 1 time.' },
  { idx: 527, level: 7, text: 'Sunrise/Sunset: Invite stranger to watch sunrise/sunset together at specific spot. Have contemplative conversation. Do 2 times.' },
  { idx: 528, level: 7, text: 'Trivia Team: Form impromptu trivia team with strangers at bar. Exchange numbers afterward to team up again. Do 1 time.' },
  { idx: 529, level: 7, text: 'Game Night: Organize game night at public space (bar, cafe). Invite strangers to join. Do 1 time.' },
  { idx: 530, level: 7, text: 'Potluck Organizer: Organize potluck with 5+ people you\'ve met through approaches. Be bridge builder. Do 1 time.' },
  { idx: 531, level: 7, text: 'Group Hike: Organize group hike with 3-5 people you\'ve met recently. Use shared activity to deepen bonds. Do 1 time.' },
  { idx: 532, level: 7, text: 'Book Club: Start small book club with 4-5 people you\'ve approached. Meet monthly to discuss. Do 1 time.' },
  { idx: 533, level: 7, text: 'Dinner Party Host: Host dinner for 6-8 people where you\'re the only connection between guests. Facilitate introductions. Do 1 time.' },
  { idx: 534, level: 7, text: 'Birthday Open Invite: On your birthday, invite 10 acquaintances from your approaches. See who shows up and build from there. Do 1 time.' },
  { idx: 535, level: 7, text: 'Spontaneous Day Trip: Invite someone you recently met on spontaneous day trip. "I\'m going to [place], want to join?" Do 2 times.' },
  { idx: 536, level: 7, text: 'Concert Buddy: Buy 2 tickets to concert. Invite someone you recently met to join you. Do 1 time.' },
  { idx: 537, level: 7, text: 'Sports Game Invite: Get tickets to local sports game. Invite new acquaintance to join. Do 1 time.' },
  { idx: 538, level: 7, text: 'Festival Together: Attend local festival and proactively meet 10 new people. Get at least 3 numbers. Follow up with all 3. Do 1 time.' },
  { idx: 539, level: 7, text: 'Travel Companion: Plan weekend trip and invite someone you recently connected with to join. Do 1 time.' },
  { idx: 540, level: 7, text: 'Road Trip: Organize multi-day road trip with 2-3 people from your recent approaches. Do 1 time.' },
  { idx: 541, level: 7, text: 'Camping Trip: Organize camping trip with small group. Use nature and downtime for deep conversations. Do 1 time.' },
  { idx: 542, level: 7, text: 'House Party: Throw house party and invite mix of close friends and people you recently approached. Do 1 time.' },
  { idx: 543, level: 7, text: 'Networking Event Hosting: Host small networking event in your area of interest. Invite 15-20 people. Do 1 time.' },
  { idx: 544, level: 7, text: 'Collaboration Project: Start creative/business project with someone you recently met. Work together on something real. Do 1 time.' },
  { idx: 545, level: 7, text: 'Accountability Partnership: Form deep accountability partnership with someone. Weekly check-ins on goals. Do 1 time.' },
  { idx: 546, level: 7, text: 'Mastermind Group: Form 4-6 person mastermind group focused on personal growth. Meet biweekly. Do 1 time.' },
  { idx: 547, level: 7, text: 'Men\'s Group: Create or join men\'s group for deep sharing and growth. Commit to 3-month minimum. Do 1 time.' },
  { idx: 548, level: 7, text: 'Support Circle: Create support circle for specific challenge (dating, career, health). Meet regularly. Do 1 time.' },
  { idx: 549, level: 7, text: 'Philosophy Discussion: Start regular philosophy/deep topics discussion group. Invite 4-8 thinkers. Do 1 time.' },
  { idx: 550, level: 7, text: 'Challenge Group: Form group to do 30-day challenge together (cold showers, daily approaches, meditation). Do 1 time.' },
  { idx: 551, level: 7, text: 'Fitness Accountability: Form fitness group with 3-5 people. Work out together 3x/week for month. Do 1 time.' },
  { idx: 552, level: 7, text: 'Creative Collective: Form creative group (writing, music, art). Meet to create together and give feedback. Do 1 time.' },
  { idx: 553, level: 7, text: 'Investment Club: Form small investment/financial literacy club. Pool knowledge and learn together. Do 1 time.' },
  { idx: 554, level: 7, text: 'Language Exchange: Form language exchange partnership. Meet weekly to practice two languages. Do 1 time.' },
  { idx: 555, level: 7, text: 'Meditation Circle: Create meditation circle. Meet weekly for group practice and discussion. Do 1 time.' },
  { idx: 556, level: 7, text: 'Breathwork Session: Organize group breathwork session. Hire facilitator or learn to lead it yourself. Do 1 time.' },
  { idx: 557, level: 7, text: 'Cold Plunge Group: Form group to do regular cold plunges together. Use shared challenge to bond. Do 1 time.' },
  { idx: 558, level: 7, text: 'Sauna Talks: Organize regular sauna sessions with different people for deep conversations. Do 3 times.' },
  { idx: 559, level: 7, text: 'Movement Practice: Start movement/dance practice group. Meet weekly to explore embodiment together. Do 1 time.' },
  { idx: 560, level: 7, text: 'Improv Group: Form improv group to practice spontaneity and yes-and thinking. Meet weekly. Do 1 time.' },
  { idx: 561, level: 7, text: 'Public Speaking: Organize Toastmasters-style group for practicing public speaking and presentations. Do 1 time.' },
  { idx: 562, level: 7, text: 'Story Circle: Create circle where people share personal stories. Practice deep listening and witnessing. Do 1 time.' },
  { idx: 563, level: 7, text: 'Men\'s Initiation: Participate in or organize men\'s initiation/rite of passage weekend retreat. Do 1 time.' },
  { idx: 564, level: 7, text: 'Silent Retreat: Organize or attend group silent retreat. Use shared silence to deepen connection. Do 1 time.' },
  { idx: 565, level: 7, text: 'Vision Quest: Participate in solo vision quest (24-48hr alone in nature). Share experience with group after. Do 1 time.' },
  { idx: 566, level: 7, text: 'Integration Circle: Create integration circle to process and integrate all your Tensey experiences. Meet monthly for 6 months. Do 1 time.' },
];

module.exports = {
  challenges: CHALLENGES,
  
  /**
   * Get challenge by index
   * @param {number} idx - Challenge index (0-566)
   * @returns {Object|null} Challenge object or null
   */
  getChallengeByIdx(idx) {
    return this.challenges.find(c => c.idx === idx) || null;
  },
  
  /**
   * Get challenges by level
   * @param {number} level - Level number (1-7)
   * @returns {Array} Array of challenges for that level
   */
  getChallengesByLevel(level) {
    return this.challenges.filter(c => c.level === level);
  },
  
  /**
   * Get level info
   * @param {number} level - Level number (1-7)
   * @returns {Object} Level metadata
   */
  getLevelInfo(level) {
    const levelChallenges = this.getChallengesByLevel(level);
    const firstIdx = levelChallenges[0]?.idx || 0;
    const lastIdx = levelChallenges[levelChallenges.length - 1]?.idx || 0;
    
    const levelNames = {
      1: 'Basic Approach & Warm-Up',
      2: 'Social Creativity & Playfulness',
      3: 'Vulnerability & Authentic Expression',
      4: 'Bold Social Experiments',
      5: 'Tension & Escalation',
      6: 'Embodied Approach Foundations',
      7: 'Deep Integration & Mastery'
    };
    
    const levelEmojis = {
      1: '🌱',
      2: '🎨',
      3: '💎',
      4: '🚀',
      5: '⚡',
      6: '🧘',
      7: '🎯'
    };
    
    return {
      level,
      name: levelNames[level] || `Level ${level}`,
      emoji: levelEmojis[level] || '🔥',
      count: levelChallenges.length,
      startIdx: firstIdx,
      endIdx: lastIdx,
      challenges: levelChallenges
    };
  }
};
